@startuml
actor Administrator

Administrator -> MainWindow : 1. addBookItem.actionPerformed(e)
activate MainWindow

MainWindow -> AddBookPanel : 2. showPanel(addBookPanel)
activate AddBookPanel

AddBookPanel -> AddBookPanel : 3. initialize()

Administrator -> AddBookPanel : 4. SubmitButtonListener.actionPerformed(e)
activate AddBookPanel

AddBookPanel -> Book : 5. new(isbn, title, maximumCheckout)

AddBookPanel -> BookCopy : 6. new(book, numberOfCopies)

Book -> BookCopy: 7. updateCopies(book)

AddBookPanel -> SystemController : 8. addNewBook(Book)
activate SystemController

SystemController -> DataAccessFacade : 9. addBook(book)
activate DataAccessFacade

DataAccessFacade -> DataAccessFacade : 10. readBooksMap()
DataAccessFacade -> DataAccessFacade : 11. saveToStorage(StorageType.BOOKS, books)

return

deactivate DataAccessFacade

deactivate SystemController

deactivate AddBookPanel

deactivate MainWindow
@enduml