@startuml
autonumber
actor Librarian
participant "MainWindow" as MW
participant "PrintCheckoutRecordPanel" as PCRP
participant "DataAccessFacade" as DAF
participant "LibraryMember" as LM
participant "Checkout" as CO

Librarian -> MW: 1. Click Print Checkout Record
activate MW
MW -> PCRP: 2. showPanel(PrintCheckoutRecordPanel)
deactivate MW
activate PCRP

PCRP -> DAF: 3. readMemberMap()
activate DAF
DAF --> PCRP: 4. Map<String, LibraryMember>
deactivate DAF

PCRP -> LM: 5. *getCheckouts()
activate LM
LM -> CO: 6. *Iterate over checkouts
activate CO
CO -> PCRP: 7. Book Title, Copy Number, Checkout Date, Due Date

PCRP -> Console: 8. Print Checkout Record

CO --> LM: 9. return
LM --> PCRP: 10. return

PCRP --> Librarian: Displayed on Console

@enduml