@startuml
autonumber
actor Administrator
activate Administrator

Administrator -> AddMemberPanel :: add Member
activate AddMemberPanel

AddMemberPanel -> AddMemberPanel :: handle
activate AddMemberPanel
Administrator -> AddMemberPanel :: submit
AddMemberPanel -> SystemController :: addNewMember
activate SystemController
deactivate AddMemberPanel

SystemController -> Address :: new
activate Address
deactivate Address

SystemController -> LibraryMember :: new
activate LibraryMember
deactivate LibraryMember

SystemController -> DataAccessFacade :: new
activate DataAccessFacade
SystemController -> DataAccessFacade :: saveNewMember

DataAccessFacade -> DataAccessFacade :: readMemberMap
activate DataAccessFacade
deactivate DataAccessFacade
DataAccessFacade -> DataAccessFacade :: saveToStorage
activate DataAccessFacade
deactivate DataAccessFacade

deactivate DataAccessFacade
deactivate SystemController

Administrator <- AddMemberPanel :: confirmationMessage
deactivate AddMemberPanel

deactivate Administrator

@enduml