@startuml

actor User

boundary "LibrarySystem" as ls
control "SystemController" as sc
entity "DataAccessFacade" as da
entity "Book" as b
entity "BookCopy" as bc
entity "Checkout" as co
entity "LibraryMember" as lm

User -> ls: searchByISBN(isbn)
ls -> sc: searchOverdueBookCopies(isbn)

sc -> da: searchBook(isbn)
da -> b: getCopies()

alt Book Exists
    b -> bc: isAvailable()
    bc -> co: getCheckout()
    co -> lm: getMember()
    co -> co: getReturnDate()
    
    alt Copy is Overdue
        ls -> User: displayCopyDetails(copyNum, member, dueDate)
    end
end

@enduml